# Generated by Django 5.2.5 on 2025-08-30 03:33

import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexaveda_user', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parent_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[validators.validate_phone_number]),
        ),
    ]
