# Generated by Django 5.2.5 on 2025-08-31 12:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexaveda_user', '0004_coursesmodel_topic_subtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursesmodel',
            name='course_progress',
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='course_cost',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='course_discount',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='course_level',
            field=models.CharField(choices=[('BEGINEER', 'BEGINEER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCED', 'ADVANCED')], default='BEGINEER', max_length=100),
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Nexaveda_user.coursesmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Nexaveda_user.coursesmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubtopicModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subtopic', models.CharField(max_length=255)),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic', to='Nexaveda_user.topicmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Subtopic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
