# Generated by Django 5.2.5 on 2025-09-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexaveda_user', '0005_remove_topic_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
