# Generated by Django 5.2.5 on 2025-09-03 04:08

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('Nexaveda_user', '0006_coursesmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='User',
            name='role',
            field = models.CharField(
                max_length=100,
                choices=[("STUDENT", "STUDENT"),("INSTRUCTOR", "INSTRUCTOR"),("ADMIN", "ADMIN")],
                default='STUDENT',
            ),
        ),
    ]
