# Generated by Django 5.2.5 on 2025-09-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexaveda_user', '0008_alter_coursesmodel_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesmodel',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
