# Generated by Django 5.2.5 on 2025-09-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexaveda_user', '0009_alter_coursesmodel_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesmodel',
            name='course_name',
            field=models.CharField(default='Python', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
