# Generated by Django 5.2.5 on 2025-09-07 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nexaveda_user', '0010_alter_coursesmodel_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='user',
            field=models.ForeignKey(default='867d4f95-559a-4b8c-ad53-b59fedf82c85', on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
